---
- name: "update apt packages."
  become: yes
  apt:
   update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
   upgrade: yes

- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: extract the zipped artifact
  become: yes
  unarchive:
    src: ../../../../../artifact.tar.gz
    dest: .

- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start